name: issue-labeller

on:
  issues:
    types: [opened]

jobs:
  automate-issues-labels:
    runs-on: ubuntu-latest
    steps:
      - name: initial issue labeling
        uses: andymckay/labeler@master
        with:
          add-labels: "needs-triage"
