name: GitHub Workflow
on:
  push:
    branches:
      - main
jobs:
  action-lint:
    name: Action Linting
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Run Action Linting
      uses: cfy9/action-linting@main
      
